PREFIX dido: <http://purl.org/twc/dido#>
PREFIX ex: <http://purl.org/twc/dido/individuals#>
PREFIX sio: <http://semanticscience.org/resource/>

# CQ1: How many participants are involved in dialogue D?
SELECT ?dialogue (COUNT(?participant) AS ?participantCount)
WHERE {
  ?participant a dido:Interlocutor ;
               sio:SIO_000062 ?dialogue .
}
GROUP BY ?dialogue
