PREFIX sio: <http://semanticscience.org/resource/>
PREFIX dido: <http://purl.org/dido#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# CQ12: What utterances were made as suggestions?
SELECT ?utterance ?text
WHERE {
  ?utterance sio:SIO_000225 ?dialogueAct . # hasFunction
  ?dialogueAct rdfs:label "Suggestion" .
  ?utterance sio:SIO_000229 ?utteranceText . # hasOutput
  ?utteranceText sio:SIO_000300 ?text . # hasValue
}