PREFIX powla: <http://purl.org/powla/powla.owl#>
PREFIX sio: <http://semanticscience.org/resource/>

# CQ13: Which interlocutor agreed with utterance?
SELECT ?agreeingInterlocutor ?agreementUtterance
WHERE {
  ?rel a powla:Relation ;
       powla:hasLabel "Agreement" ;
       powla:hasTarget ?originalUtterance ;
       powla:hasSource ?agreementUtterance .
       
  ?agreementUtterance sio:SIO_000063 ?agreeingInterlocutor . # isAgentIn
}