PREFIX sio: <http://semanticscience.org/resource/>
PREFIX dido: <http://purl.org/dido#>

# CQ14: Which interlocutor made a particular assertion?
SELECT ?interlocutor ?assertion
WHERE {
  ?utterance dido:supports ?assertion .
  ?utterance sio:SIO_000139 ?interlocutor . # hasAgent
}