PREFIX sio: <http://semanticscience.org/resource/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX powla: <http://purl.org/powla/powla.owl#>
PREFIX dido: <http://purl.org/dido#>

# CQ18: Which interlocutor revised their stance on an assertion?
SELECT ?interlocutor ?assertion
WHERE {
  # Initial stance
  ?u1 dido:supports ?assertion ;
      sio:SIO_000139 ?interlocutor ; # hasAgent
      sio:SIO_000008 ?duration1 . # hasAttribute
  ?duration1 time:hasBeginning ?start1 .

  # Revision stance
  ?u2 sio:SIO_000139 ?interlocutor ; # hasAgent
      sio:SIO_000008 ?duration2 .
  ?duration2 time:hasBeginning ?start2 .
  
  # Discourse relation marking revision
  ?drAnnotation a dido:DiscourseRelationAnnotation ;
                sio:SIO_000332 ?rel ;
                sio:SIO_000300 "Revision" .
  ?rel a dido:DiscourseRelation ;
       sio:SIO_000253 ?u2 ; # hasSource
       sio:SIO_000291 ?u1 . # hasTarget

  FILTER(?start2 > ?start1)
}