PREFIX dido: <http://purl.org/dido#>
PREFIX sio: <http://semanticscience.org/resource/>

# CQ 19: Which assertions did interlocutor assert?
SELECT DISTINCT ?interlocutor ?assertion
WHERE {
  ?utterance sio:SIO_000139 ?interlocutor . # hasAgent
  ?utterance dido:supports ?assertion .
}