PREFIX dido: <http://purl.org/dido#>
PREFIX sio: <http://semanticscience.org/resource/>

# CQ2: What is the textual content of turn?
SELECT ?turn ?text
WHERE {
  ?turn a dido:Turn .
  ?turn sio:SIO_000229 ?turnText .
  ?turnText sio:SIO_000300 ?text .
}
