PREFIX dido: <http://purl.org/twc/dido#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX ex: <http://purl.org/twc/dido/individuals#>

# CQ2: Which participant is associated with turn T?
SELECT ?turn ?participant
WHERE {
  ?turn a dido:Turn .
  ?turn sio:SIO_000139 ?participant .
  ?participant sio:SIO_000228 ?role .
  ?role a dido:Interlocutor .
}
