PREFIX dido: <http://purl.org/dido#>
PREFIX sio: <http://semanticscience.org/resource/>

# CQ3: Which participant produced turn?
SELECT ?turn ?participant
WHERE {
  ?turn a dido:Turn .
  ?turn sio:SIO_000063 ?participant .
}
