PREFIX dido: <http://purl.org/twc/dido#>
PREFIX sio: <http://semanticscience.org/resource/>

# CQ4: Is participant a human or a software agent?
SELECT ?participant ?type
WHERE {
  ?participant a ?type .
  FILTER(?type IN (sio:SIO_000097, sio:SIO_000485))
}
