PREFIX dido: <http://purl.org/twc/dido#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX time: <http://www.w3.org/2006/time#>

# CQ5: Which turn most closely follows turn?
SELECT ?turn ?follower
WHERE {
  ?turn a dido:Turn ;
      sio:SIO_000008 [ time:hasEnd [ time:inDateTime [ time:second ?uEnd ] ] ] .
  ?follower a dido:Turn ;
      sio:SIO_000008 [ time:hasBeginning [ time:inDateTime [ time:second ?fStart ] ] ] .
  
  FILTER (?fStart >= ?uEnd)
  
  # Ensure no other turn starts between them
  FILTER NOT EXISTS {
    ?other a dido:Turn ;
           sio:SIO_000008 [ time:hasBeginning [ time:inDateTime [ time:second ?otherStart ] ] ] .
    FILTER (?otherStart >= ?uEnd && ?otherStart < ?fStart)
  }
}
