PREFIX dido: <http://purl.org/twc/dido#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX time: <http://www.w3.org/2006/time#>

# CQ6: Which turns occured between time T1 and time T2?
SELECT ?turn ?startTime ?endTime
WHERE {
  ?turn a dido:Turn ;
             sio:SIO_000008 [ 
               time:hasBeginning [ time:inDateTime [ time:second ?startTime ] ] ;
               time:hasEnd [ time:inDateTime [ time:second ?endTime ] ]
             ] .
  
  FILTER (?startTime >= "0"^^xsd:decimal && ?endTime <= "15"^^xsd:decimal)
}
ORDER BY ?startTime
